### ISSUE TITLE
[PE-D][Tester D] Empty email search throws Exception

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-F14-2/tp#206]
find e/ throws Exception (StackTrace)

![image.png](https://raw.githubusercontent.com/cheeheng/ped/main/files/dc48bf38-bd9a-405c-851a-7c8ebdd13ead.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cheeheng/ped#2

**Comment by lulucopter** [comment]
Same bug as #189
