### ISSUE TITLE
Suggestion: Find Command Message

### ISSUE THREAD

**Issue by JasonCP14** [AY2223S1-CS2103-F14-2/tp#291]
Maybe you would want to follow the edit command message **(look at the square brackets)** below to make it clearer. 

<img width="496" alt="image" src="https://user-images.githubusercontent.com/88238739/200180737-94a6aed2-906c-434c-852e-37650bed9bce.png">

**Comment by lulucopter** [comment]
Thanks for the suggestion. My original intention was to not clutter the Ui, and to indicate that at least 1 option is compulsory. Think i'll follow the edit command message format for consistency
